"""A tiny distillation corpus for chapter 4 — deliberately small so it trains in
minutes on a laptop CPU with the fan barely spinning. In the real DeepSpec recipe
this is a huge cache of the target's own generations; here a few dozen lines are
enough to show acceptance climb. We distill to the TARGET's next tokens, not to
this text, so the drafter learns to imitate the target, not to memorise these
sentences."""

SENTENCES = [
    "The key idea behind speculative decoding is to let a small model guess several tokens ahead.",
    "A large language model generates text one token at a time, which is slow.",
    "Once upon a time, in a small village by the sea, there lived a curious child.",
    "def add(a, b):\n    return a + b\n",
    "def fibonacci(n):\n    if n < 2:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)\n",
    "Water boils at one hundred degrees Celsius at sea level under normal pressure.",
    "The mitochondria is often called the powerhouse of the cell.",
    "To train a neural network, we minimise a loss function using gradient descent.",
    "In the beginning the universe was created, which made a lot of people very angry.",
    "The quick brown fox jumps over the lazy dog near the river bank.",
    "Machine learning models learn patterns from data instead of following fixed rules.",
    "Paris is the capital of France, and it sits on the banks of the river Seine.",
    "for i in range(10):\n    print(i * i)\n",
    "A speculative decoder is only faster when the draft model guesses correctly often.",
    "The sun rose slowly over the mountains, painting the sky in shades of orange and pink.",
    "import torch\nimport torch.nn as nn\n",
    "Attention lets each token in a sequence look at every other token to gather context.",
    "The recipe calls for two cups of flour, one egg, and a pinch of salt.",
    "Gradient descent takes small steps downhill to reduce the error of the model.",
    "She opened the old wooden door and stepped into a room full of dusty books.",
    "A transformer is built from stacked layers of attention and feed-forward networks.",
    "The stock market rose sharply today after the company reported strong earnings.",
    "class Animal:\n    def speak(self):\n        raise NotImplementedError\n",
    "Photosynthesis converts sunlight, water, and carbon dioxide into sugar and oxygen.",
    "The verifier checks each drafted token against the target model in a single pass.",
    "He walked along the quiet beach at dawn, listening to the gentle sound of the waves.",
    "Tokens are the small pieces of text that a language model reads and writes.",
    "The capital of Japan is Tokyo, one of the largest cities in the entire world.",
    "We accept the longest prefix of guesses that the target model would have produced.",
    "Reading a good book on a rainy afternoon is one of life's simple pleasures.",
    "The old fisherman mended his nets slowly while the tide crept up the shore.",
    "After many years of travel, she finally returned to the town where she was born.",
    "The engineer studied the blueprint carefully before approving the final design.",
    "A gentle rain fell over the city as the last train pulled out of the station.",
    "The scientist recorded her observations in a worn leather notebook every night.",
    "When the power went out, the whole neighbourhood gathered outside to talk.",
    "The bakery smelled of fresh bread and cinnamon early on Sunday mornings.",
    "He tightened the last bolt, wiped his hands, and stepped back to admire the engine.",
    "The children built an enormous sandcastle and defended it from the rising sea.",
    "In autumn the maple trees turned a deep red that lit up the entire valley.",
    "The librarian recommended a quiet novel about a long journey across the desert.",
    "A single candle flickered in the window of the cottage at the edge of the forest.",
    "The startup spent months rewriting its backend before the big product launch.",
    "Every morning the baker unlocked the shop and set out warm loaves on the counter.",
    "The mountain path grew steeper as the hikers climbed toward the hidden lake.",
    "She practised the same difficult passage on the piano until it finally sounded right.",
    "The captain checked the compass twice before steering the ship into open water.",
    "A curious cat followed the delivery driver all the way down the narrow street.",
    "The professor explained the proof again, drawing careful diagrams on the board.",
    "Under the bright stadium lights the runners lined up and waited for the signal.",
]
